CREATE TABLE SAILOR
(
  SID INT PRIMARY KEY,
  NAME VARCHAR(50),
  RATING INT CONSTRAINT r CHECK (RATING>=6 AND RATING<=10),
  AGE INT
);

CREATE SEQUENCE SAILOR_ID
START WITH 1
INCREMENT BY 1
MINVALUE 1
MAXVALUE 10
NOCYCLE;

DROP TABLE SAILOR
DROP SEQUENCE SAILOR_ID

INSERT INTO SAILOR VALUES(SAILOR_ID.NEXTVAL, 'Jack Sparrow', 10, 40);
INSERT INTO SAILOR VALUES(SAILOR_ID.NEXTVAL, 'Will Turner', 6, 26);
INSERT INTO SAILOR VALUES(SAILOR_ID.NEXTVAL, 'Horatio', 7, 24);
INSERT INTO SAILOR VALUES(SAILOR_ID.NEXTVAL, 'Gibbs', 9, 51);
INSERT INTO SAILOR VALUES(SAILOR_ID.NEXTVAL, 'Davey Jones', 10, 42);
INSERT INTO SAILOR VALUES(SAILOR_ID.NEXTVAL, 'Julius', 9, 25);

UPDATE SAILOR SET NAME = UPPER(NAME); 

select * from sailor 
DROP TABLE SAILOR
DROP SEQUENCE SAILOR_ID


CREATE TABLE BOAT
(
  BID INT PRIMARY KEY,
  NAME VARCHAR(50),
  COLOUR VARCHAR(30)
);

CREATE SEQUENCE BOAT_ID
START WITH 100
INCREMENT BY 1
MINVALUE 100
MAXVALUE 110
NOCYCLE;

DROP TABLE BOAT
DROP SEQUENCE BOAT_ID

INSERT INTO BOAT VALUES(BOAT_ID.NEXTVAL, 'Black Pearl', 'Black');
INSERT INTO BOAT VALUES(BOAT_ID.NEXTVAL, 'Queen Annes Revenge', 'Red');
INSERT INTO BOAT VALUES(BOAT_ID.NEXTVAL, 'Blackbeards Delight', 'Black');
INSERT INTO BOAT VALUES(BOAT_ID.NEXTVAL, 'Redbeards Delight', 'Red');
INSERT INTO BOAT VALUES(BOAT_ID.NEXTVAL, 'Oceans Dagger', 'Blue');
INSERT INTO BOAT VALUES(BOAT_ID.NEXTVAL, 'Marine', 'Blue');
INSERT INTO BOAT VALUES(BOAT_ID.NEXTVAL, 'Interlake', 'Red');

select * from boat

CREATE TABLE RESERVATION
(
  SID INT,
  BID INT,
  DAY DATE,
  CONSTRAINT FK_SID FOREIGN KEY (SID) REFERENCES SAILOR (SID),
  CONSTRAINT FK_BID FOREIGN KEY (BID) REFERENCES BOAT (BID),
  PRIMARY KEY(SID, BID, DAY)
);

DROP TABLE RESERVATION

INSERT INTO RESERVATION VALUES (2, 101, '11-FEB-2016');
INSERT INTO RESERVATION VALUES (6, 107, '10-JUN-2016');
INSERT INTO RESERVATION VALUES (1, 101, '10-OCT-2016');
INSERT INTO RESERVATION VALUES (1, 101, '10-OCT-2017');
INSERT INTO RESERVATION VALUES (1, 102, '10-JUL-2017');
INSERT INTO RESERVATION VALUES (1, 101, '10-JUL-2017');
INSERT INTO RESERVATION VALUES (2, 102, '11-SEP-2017');
INSERT INTO RESERVATION VALUES (2, 102, '7-NOV-2017');
INSERT INTO RESERVATION VALUES (3, 101, '7-NOV-2017');
INSERT INTO RESERVATION VALUES (3, 102, '7-AUG-2017');
INSERT INTO RESERVATION VALUES (4, 103, '19-SEP-2017');
INSERT INTO RESERVATION VALUES (6, 104, '19-SEP-2017');

SELECT COUNT(*) FROM BOAT WHERE COLOUR = 'Black';
SELECT DISTINCT(SID) FROM RESERVATION R, BOAT B WHERE B.BID = R.BID AND (B.COLOUR = 'Red' OR B.COLOUR = 'Green');
SELECT NAME, AGE FROM SAILOR WHERE AGE = (SELECT MIN(AGE) FROM SAILOR);
SELECT S.SID, S.NAME, S.AGE FROM RESERVATION R, SAILOR S WHERE S.SID = R.SID AND R.BID = 101; 
SELECT DISTINCT(S.NAME) FROM RESERVATION R, SAILOR S WHERE S.SID != R.SID ORDER BY S.NAME;
SELECT B.COLOUR FROM BOAT B, SAILOR S, RESERVATION R WHERE R.BID = B.BID AND R.SID = S.SID AND S.NAME = 'Horatio';

SELECT COUNT(DISTINCT B.BID) FROM RESERVATION R, BOAT B WHERE R.BID = B.BID AND B.COLOUR = 'Red' AND /*YEAR = 2017*/;

SELECT SID FROM SAILOR WHERE RATING = (SELECT MAX(RATING) FROM SAILOR);

SELECT S.SID, S.NAME, S.AGE FROM RESERVATION R, SAILOR S, BOAT B WHERE S.SID=R.SID

SELECT NAME FROM SAILOR WHERE RATING > (SELECT RATING FROM SAILOR WHERE NAME = 'GIBBS');

SELECT DISTINCT(SID) FROM RESERVATION NATURAL JOIN BOAT WHERE COLOUR = 'Red' OR COLOUR = 'Green';

SELECT SID, NAME, AGE FROM RESERVATION NATURAL JOIN SAILOR WHERE BID = 101;

SELECT SID FROM SAILOR MINUS SELECT DISTINCT(SID) FROM RESERVATION;

SELECT SID FROM SAILOR WHERE RATING > (SELECT RATING FROM SAILOR WHERE NAME = 'ZORBA');

SELECT SID, NAME, AGE FROM SAILORS NATURAL JOIN BOAT NATURAL JOIN RESERVATIONS WHERE COUNT(DISTINCT BID) = 1

SELECT SID FROM SAILOR MINUS SELECT SID FROM RESERVATION WHERE BID = (SELECT BID FROM BOAT WHERE COLOUR = 'Red');


